export default {
  port: "PORT",
  dbUserName: "MONGODB_USERNAME",
  dbUserPassword: "MONGODB_PASSWORD",
  dbName: "MONGODB_NAME",
  devOrigin: "DEV_ORIGIN",
  prodOrigin: "PROD_ORIGIN",
  accessTokenPrivateKey: "ACCESS_TOKEN_PRIVATE_KEY",
  accessTokenPublicKey: "ACCESS_TOKEN_PUBLIC_KEY",
  refreshTokenPrivateKey: "REFRESH_TOKEN_PRIVATE_KEY",
  refreshTokenPublicKey: "REFRESH_TOKEN_PUBLIC_KEY",
  from: "EMAIL_FROM",
  smtp: {
    user: "SMTP_USERNAME",
    pass: "SMTP_PASSWORD",
    host: "SMTP_HOST",
    port: "SMTP_PORT",
  },
  sendgridUser: "SENDGRID_USERNAME",
  sendgridPass: "SENDGRID_PASSWORD",
  payPalClientId: "PAYPAL_CLIENT_ID",
  stripeSecretKey: "STRIPE_SECRET_KEY",
  stripePublishableKey: "STRIPE_PUBLISHABLE_KEY",
};
